name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
        
      - name: Setup goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run build script
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build GCP Docker image
        run: gcloud builds submit --tag northamerica-northeast2-docker.pkg.dev/notely-426304/notely-ar-repo/notely:latest .

      - name: Goose migrate up
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image northamerica-northeast2-docker.pkg.dev/notely-426304/notely-ar-repo/notely:latest --region northamerica-northeast2 --allow-unauthenticated --project notely-426304 --max-instances=4